---
title: "safe_babies"
author: "Santhosh reddy Mallikireddy"
date: "28/02/2020"
output:
  html_document: default
  pdf_document: default
---
```{r}
library(ISLR)
library(dplyr)
library(gridExtra)
library(ggplot2)
```


```{r}
#importing safeBabies dataset
SafeBabies <- Carseats %>% select("Sales", "Price", "ShelveLoc")
#filtering dataset into good,medium and bad
good <- filter(SafeBabies,ShelveLoc == 'Good')
medium <- filter(SafeBabies,ShelveLoc == 'Medium')
bad <- filter(SafeBabies,ShelveLoc == 'Bad')
```


```{r}
good1<-good[order(good$Price),]
Model_1 <- lm(good1$Sales ~ good1$Price, data = good1)
summary(Model_1)
#optimal price for car seats in good shelves
optimal_price_good = (-0.065785 *55 - 17.968864)/(2 * -0.065785)
optimal_price_good
optimised_results_good <- function() {
  for(cost in 40:85) {
    optimised_results_good<- (-0.065785 *cost - 17.968864)/(2 * -0.065785)
    print(optimised_results_good)
  }
  
}
price<- c(40:85)
optimized_price<-c(156.5727, 157.0727, 157.5727, 158.0727, 158.5727, 159.0727, 159.5727, 160.0727, 160.5727, 161.0727, 161.5727, 162.0727, 162.5727, 163.0727, 163.5727, 164.0727, 164.5727, 165.0727, 165.5727, 166.0727, 166.5727, 167.0727, 167.5727, 168.0727, 168.5727, 169.0727, 169.5727, 170.0727, 170.5727, 171.072, 171.5727, 172.0727, 172.5727, 173.0727, 173.5727, 174.0727, 174.5727, 175.0727, 175.5727, 176.0727, 176.5727, 177.0727, 177.5727, 178.0727, 178.5727, 179.0727)
optimized_price_good<-cbind.data.frame(optimized_price,price)
names(optimized_price_good)<-c('Optimized Price','Change in Cost')
head(optimized_price_good)

good_plot<-ggplot(optimized_price_good, aes(optimized_price_good$`Optimized Price`, optimized_price_good$`Change in Cost`, colour='Good')  ) + labs(title = 'Optimized Price VS Cost Price',x='Optimized price',y='Cost Price') + geom_line() +  scale_color_manual("", values = ("Good" = "green")) +geom_point(colour='black')
good_plot
```


```{r}
bad1<-bad[order(bad$Price),]
ncol(bad1)
Model_2 <- lm(bad1$Sales ~ bad1$Price, data = bad1)
summary(Model_2)
Optimum_price_bad = (-0.05522 * 55 - 11.832984) / (2 * -0.05522)
Optimum_price_bad
optimised_results_bad.function <- function() {
  for(cost in 40:85) {
    optimised_results_bad<- (-0.05522 *cost - 11.832984)/(2 * -0.05522)
    print(optimised_results_bad)
  }
  
}   
price1<- c(40:85)
optimize_bad<-c(127.144, 127.644, 128.144, 128.644, 129.144, 129.644, 130.144, 130.644, 131.144, 131.644, 132.144, 132.644, 133.144, 133.644, 134.144, 134.644, 135.144, 135.644, 136.144, 136.644, 137.144, 137.644, 138.144, 138.644, 139.144, 139.644, 140.144, 140.644, 141.144, 141.644, 142.144, 142.644, 143.144, 143.644, 144.144, 144.644, 145.144, 145.644, 146.144, 146.644, 147.144, 147.644, 148.144, 148.644, 149.144, 149.644)

optimized_price_bad<-cbind.data.frame(optimize_bad,price1)
names(optimized_price_bad)<-c('Optimized Price','Change in Cost')
head(optimized_price_bad)

bad_plot<-ggplot(optimized_price_bad, aes(optimized_price_bad$`Optimized Price`, optimized_price_bad$`Change in Cost`, colour='bad')  ) + labs(x='Optimized price',y='Cost Price') + geom_line() +  scale_color_manual("", values = ("bad" = "red")) +geom_point(colour='black')
bad_plot
grid.arrange(good_plot, bad_plot, ncol=1)
```

